export enum SOCKET {
  JOIN_ROOM = 'joinRoom',
  JOINED_ROOM = 'joinedRoom',
  START_QUIZ = 'startQuiz',
  END_QUIZ = 'endQuiz',
  STUDENT_LIST_UPDATE = 'studentListUpdate',
  STUDENT_LISTS = 'studentLists',
  QUIZ_LIST = 'quizList',
  ANSWER = 'answer',
  ANSWER_IS_CORRECT = 'answerIsCorrect',
  RESULT = 'result',
  RECONNECT_STUDENT = 'reconnectStudent',
  RECONNECTED = 'reconnected',
  ERROR = 'error',
}
